version: '3.7'

services:
  elastalert:
    image: 223455578796.dkr.ecr.us-west-2.amazonaws.com/monitor-elastalert:latest
    restart: always
    container_name: elastalert
    ports:
      - 3030:3030
      - 3333:3333
    volumes:
      - $PWD/config/elastalert.yaml:/opt/elastalert/config.yaml:ro
      - $PWD/config/config.json:/opt/elastalert-server/config/config.json:ro
      - $PWD/rules:/opt/elastalert/rules
    extra_hosts:
      - "es_host:44.225.165.227"